services:
  database:
    image: "postgres:15"
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    volumes:
      - postgresql_data:/var/lib/postgresql/database


volumes:
  postgresql_data: